version: '3.4'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27019:27017
    volumes:
      - mongodb_data_container:/data/db
      
volumes:
  mongodb_data_container:

networks: 
  broker-validacao-senha:
    driver: bridge